### ISSUE TITLE
lab1 / episode_1 : масштаб по осям

### ISSUE THREAD

**Issue by avasyukov** [fr1bze/python_labs_3sem#1]
Сейчас масштаб по осям сильно разный по OX и по OY. В итоге, например, длинная и тонкая область визуально выглядит как почти квадратик. А условный кружочек превращается в эллипс. Например, вот здесь - http://judge2.vdi.mipt.ru/ejudge/lab_01_mpl/003.png - три точки слева лежат примерно на дуге окружности. И при взгляде глазами на картинку это видно. А на третьем графике лабы сейчас - совсем не видно.

В условии было, что масштаб должен быть зафиксирован. Это нужно поправить.

**Comment by fr1bze** [comment]
Исправил, на скринах моих теперь вроде схоже с тем, что можно наблюдать на вашем
![003](https://user-images.githubusercontent.com/76403523/145706290-5caaffd2-64d7-401c-ba85-619de6019fb2.jpg)

**Comment by avasyukov** [comment]
Ок
