### ISSUE TITLE
lab1 / episode_2 : работа с тиками

### ISSUE THREAD

**Issue by avasyukov** [fr1bze/python_labs_3sem#3]
Кажется, тут есть лишние движения:
https://github.com/fr1bze/python_labs_3sem/blob/03041faa363506d56a133fb233c7586656522323/lab_1/episode_2%20/epis2.py#L16-L19

Нужно или поправить, или объяснить, почему они не лишние.

**Comment by fr1bze** [comment]
В целом согласен, есть лишнее, но для того чтобы было как и на скрине, решил сделать тики, убрал 2 строчки по сути не очень нужные и немного переделал код

**Comment by avasyukov** [comment]
Ок
