### ISSUE TITLE
lab2 / episode_3 : данные в ответах

### ISSUE THREAD

**Issue by avasyukov** [fr1bze/python_labs_3sem#7]
В задании просили:
1. На графиках количество решённых задач, а не баллов.
2. В последней выборке смотреть на две задачи - G и H.

**Comment by fr1bze** [comment]
Пункт 2 исправлен: 
`data_all_res_inf_gr = data_all[(data_all['G'] > 10) | (data_all['H'] > 10)].groupby(by = 'group_out', as_index=False).count()`

**Comment by fr1bze** [comment]
Пункт 1 исправлен: 
![results](https://user-images.githubusercontent.com/76403523/145711178-b13888b6-9795-4ace-b42a-23ac478c37a5.png)

**Comment by avasyukov** [comment]
Ок
